# Configuration mgrep pour weekend-checker
# Le store utilise automatiquement le nom du dossier: weekend-checker

# Taille maximale des fichiers (hérite de la config globale si non spécifié)
# maxFileSize: 10485760

# Nombre maximum de fichiers
# maxFileCount: 10000
